@startuml c1
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

title Диаграмма контекста для "Теплый дом" Монолит AS-IS

Person(user, "Пользователь", "Клиент системы умного дома, только отопление")
System_Ext(modules, "Датчики", "Датчики и модули для управления умным домом только отопление")
System(system, "Теплый дом монолит", "Приложение управления умным домом только отопление")

Rel(user, system, "Управляет состоянием дома", "только отопление,получает данные с датчиков и может включить и отключить отопление ..")
Rel(system, modules, "Контролирует целевые показатели", "только температура, ...")

@enduml